#ifndef	_KBD_AT_SET2_H
#define _KBD_AT_SET2_H  1
// AT keyboard scancode set 2
#define KBD2(x)   KBD_SCANSET2_CODE_ ## x
#define KBD2E(x)  KBD_SCANSET2_CODE_EXT_ ## x

// control codes

#define KBD_SCANSET2_CODE_RESET_OK  0xAA
#define KBD_SCANSET2_CODE_PAUSE  0xE1
#define KBD_SCANSET2_CODE_EXT    0xE0
#define KBD_SCANSET2_CODE_BREAK  0xF0

#define KBD_SCANSET2_CODE_SET_LEDS  0xED
#define KBD_SCANSET2_CODE_ECHO   0xEE
#define KBD_SCANSET2_CODE_ACK    0xFA
#define KBD_SCANSET2_CODE_GET_ID  0xF2
#define KBD_SCANSET2_CODE_ERROR  0xFF
#define KBD_SCANSET2_CODE_RESET  KBD_SCANSET2_CODE_ERROR

// regular codes

#define KBD_SCANSET2_CODE_0  0x45
#define KBD_SCANSET2_CODE_1  0x16
#define KBD_SCANSET2_CODE_2  0x1E
#define KBD_SCANSET2_CODE_3  0x26
#define KBD_SCANSET2_CODE_4  0x25
#define KBD_SCANSET2_CODE_5  0x2E
#define KBD_SCANSET2_CODE_6  0x36
#define KBD_SCANSET2_CODE_7  0x3D
#define KBD_SCANSET2_CODE_8  0x3E
#define KBD_SCANSET2_CODE_9  0x46

#define KBD_SCANSET2_CODE_A  0x1C
#define KBD_SCANSET2_CODE_B  0x32
#define KBD_SCANSET2_CODE_C  0x21
#define KBD_SCANSET2_CODE_D  0x23
#define KBD_SCANSET2_CODE_E  0x24
#define KBD_SCANSET2_CODE_F  0x2B
#define KBD_SCANSET2_CODE_G  0x34
#define KBD_SCANSET2_CODE_H  0x33
#define KBD_SCANSET2_CODE_I  0x43
#define KBD_SCANSET2_CODE_J  0x3B
#define KBD_SCANSET2_CODE_K  0x42
#define KBD_SCANSET2_CODE_L  0x4B
#define KBD_SCANSET2_CODE_M  0x3A
#define KBD_SCANSET2_CODE_N  0x31
#define KBD_SCANSET2_CODE_O  0x44
#define KBD_SCANSET2_CODE_P  0x4D
#define KBD_SCANSET2_CODE_Q  0x15
#define KBD_SCANSET2_CODE_R  0x2D
#define KBD_SCANSET2_CODE_S  0x1B
#define KBD_SCANSET2_CODE_T  0x2C
#define KBD_SCANSET2_CODE_U  0x3C
#define KBD_SCANSET2_CODE_V  0x2A
#define KBD_SCANSET2_CODE_W  0x1D
#define KBD_SCANSET2_CODE_X  0x22
#define KBD_SCANSET2_CODE_Y  0x35
#define KBD_SCANSET2_CODE_Z  0x1A

#define KBD_SCANSET2_CODE_BRACKET_LEFT  0x54
#define KBD_SCANSET2_CODE_BRACKET_RIGHT  0x5B
#define KBD_SCANSET2_CODE_SLASH  0x4A
#define KBD_SCANSET2_CODE_BACKSLASH  0x5D
#define KBD_SCANSET2_CODE_MINUS  0x4E
#define KBD_SCANSET2_CODE_EQUALS  0x55
#define KBD_SCANSET2_CODE_COMMA  0x41
#define KBD_SCANSET2_CODE_SEMICOLON  0x4C
#define KBD_SCANSET2_CODE_DOT  0x49
#define KBD_SCANSET2_CODE_QUOTE  0x52
#define KBD_SCANSET2_CODE_GRAVE  0x0E

#define KBD_SCANSET2_CODE_SPACE  0x29
#define KBD_SCANSET2_CODE_TAB  0x0D
#define KBD_SCANSET2_CODE_BACKSPACE  0x66
#define KBD_SCANSET2_CODE_ENTER  0x5A
#define KBD_SCANSET2_CODE_ESC  0x76

#define KBD_SCANSET2_CODE_F1  0x05
#define KBD_SCANSET2_CODE_F2  0x06
#define KBD_SCANSET2_CODE_F3  0x04
#define KBD_SCANSET2_CODE_F4  0x0C
#define KBD_SCANSET2_CODE_F5  0x03
#define KBD_SCANSET2_CODE_F6  0x0B
#define KBD_SCANSET2_CODE_F7  0x83
#define KBD_SCANSET2_CODE_F8  0x0A
#define KBD_SCANSET2_CODE_F9  0x01
#define KBD_SCANSET2_CODE_F10  0x09
#define KBD_SCANSET2_CODE_F11  0x78
#define KBD_SCANSET2_CODE_F12  0x07

#define KBD_SCANSET2_CODE_NUM_LOCK  0x77
#define KBD_SCANSET2_CODE_CAPS_LOCK  0x58
#define KBD_SCANSET2_CODE_SCROLL_LOCK  0x7E

#define KBD_SCANSET2_CODE_L_ALT  0x11
#define KBD_SCANSET2_CODE_L_CTRL  0x14
#define KBD_SCANSET2_CODE_L_SHIFT  0x12
#define KBD_SCANSET2_CODE_R_SHIFT  0x59

#define KBD_SCANSET2_CODE_PAD_0  0x70
#define KBD_SCANSET2_CODE_PAD_1  0x69
#define KBD_SCANSET2_CODE_PAD_2  0x72
#define KBD_SCANSET2_CODE_PAD_3  0x7A
#define KBD_SCANSET2_CODE_PAD_4  0x6B
#define KBD_SCANSET2_CODE_PAD_5  0x73
#define KBD_SCANSET2_CODE_PAD_6  0x74
#define KBD_SCANSET2_CODE_PAD_7  0x6C
#define KBD_SCANSET2_CODE_PAD_8  0x75
#define KBD_SCANSET2_CODE_PAD_9  0x7D
#define KBD_SCANSET2_CODE_PAD_PLUS  0x79
#define KBD_SCANSET2_CODE_PAD_MINUS  0x7B
#define KBD_SCANSET2_CODE_PAD_TIMES  0x7C
#define KBD_SCANSET2_CODE_PAD_DOT  0x71

// extended codes
#define  KBD_SCANSET2_CODE_EXT_R_ALT  0x11
#define  KBD_SCANSET2_CODE_EXT_R_CTRL  0x14
#define  KBD_SCANSET2_CODE_EXT_L_WIN  0x1F
#define  KBD_SCANSET2_CODE_EXT_R_WIN  0x27
#define  KBD_SCANSET2_CODE_EXT_MENU 0x2F

#define  KBD_SCANSET2_CODE_EXT_PAD_DIVIDE  0x4A
#define  KBD_SCANSET2_CODE_EXT_PAD_ENTER  0x5A

#define  KBD_SCANSET2_CODE_EXT_END  0x69
#define  KBD_SCANSET2_CODE_EXT_HOME  0x6C
#define  KBD_SCANSET2_CODE_EXT_INSERT  0x70
#define  KBD_SCANSET2_CODE_EXT_DELETE  0x71
#define  KBD_SCANSET2_CODE_EXT_PAGE_DOWN  0x7A
#define  KBD_SCANSET2_CODE_EXT_PAGE_UP  0x7D
#define  KBD_SCANSET2_CODE_EXT_ARROW_LEFT  0x6B
#define  KBD_SCANSET2_CODE_EXT_ARROW_DOWN  0x72
#define  KBD_SCANSET2_CODE_EXT_ARROW_RIGHT  0x74
#define  KBD_SCANSET2_CODE_EXT_ARROW_UP  0x75
#define  KBD_SCANSET2_CODE_EXT_LEFT  0x6B
#define  KBD_SCANSET2_CODE_EXT_DOWN  0x72
#define  KBD_SCANSET2_CODE_EXT_RIGHT  0x74
#define  KBD_SCANSET2_CODE_EXT_UP  0x75

#define  KBD_SCANSET2_CODE_EXT_PRINT_SCREEN  0x12
#define  KBD_SCANSET2_CODE_EXT_PRINT_SCREEN_2  0x7C
#define  KBD_SCANSET2_CODE_EXT_PAUSE_BREAK  0x7E

#define  KBD_SCANSET2_CODE_EXT_ACPI_POWER  0x37
#define  KBD_SCANSET2_CODE_EXT_ACPI_SLEEP  0x3F
#define  KBD_SCANSET2_CODE_EXT_ACPI_WAKE  0x5E

#define  KBD_SCANSET2_CODE_EXT_MEDIA_NEXT_TRACK  0x4D
#define  KBD_SCANSET2_CODE_EXT_MEDIA_PREV_TRACK  0x15
#define  KBD_SCANSET2_CODE_EXT_MEDIA_STOP  0x3B
#define  KBD_SCANSET2_CODE_EXT_MEDIA_PLAY_PAUSE  0x34
#define  KBD_SCANSET2_CODE_EXT_MEDIA_MUTE  0x23
#define  KBD_SCANSET2_CODE_EXT_MEDIA_VOLUME_UP  0x32
#define  KBD_SCANSET2_CODE_EXT_MEDIA_VOLUME_DOWN  0x21
#define  KBD_SCANSET2_CODE_EXT_MEDIA_SELECT  0x50
#define  KBD_SCANSET2_CODE_EXT_SYS_E_MAIL  0x48
#define  KBD_SCANSET2_CODE_EXT_SYS_CALCULATOR  0x2B
#define  KBD_SCANSET2_CODE_EXT_SYS_MY_COMPUTER  0x40
#define  KBD_SCANSET2_CODE_EXT_WWW_SEARCH  0x10
#define  KBD_SCANSET2_CODE_EXT_WWW_HOME  0x3A
#define  KBD_SCANSET2_CODE_EXT_WWW_BACK  0x38
#define  KBD_SCANSET2_CODE_EXT_WWW_FORWARD  0x30
#define  KBD_SCANSET2_CODE_EXT_WWW_STOP  0x28
#define  KBD_SCANSET2_CODE_EXT_WWW_REFRESH  0x20
#define  KBD_SCANSET2_CODE_EXT_WWW_FAVORITES  0x18
 
#endif // _KBD_AT_SET2_H
